### ISSUE TITLE
Create a Docker file

### ISSUE THREAD

**Issue by mpwaller** [asimnajibi/test#2]
I would like to be able to run your app using docker. 

I want to be able to build a docker image 

``` docker build -f Dockerfile -t test:v1  . ``` 

and then run the image.

``` docker run test:v1  ```

It should print ```hello world!```

**Comment by mpwaller** [comment]
Excellent, it works.

**Comment by asimnajibi** [comment]
I have added a Dockerfile to this repository. The image can now be created:

` docker build -t test:v1 https://github.com/asimnajibi/test.git#main`

And run:

`docker run test:v1`
